# Mise will automatically read and use .tool-versions files as well as this file.

[settings]
experimental = true

[env]
# See env.example to configure API keys.
_.file = ".env"

[tools]
pnpm = "10.26.2"

[hooks]
postinstall = "pnpm install"
