# Mise will automatically read and use .tool-versions files as well as this file.
[settings]
experimental=true

[env]
# See env.example to configure API keys.
_.file = ".env"

[tools]
uv = "latest"
temporal = "latest"
overmind = "latest"

[hooks]
postinstall = "mise run install"

[tasks.install]
description = "Install requirements"
run = "uv pip install -r requirements.txt"

[tasks.server]
description = "Run temporal server"
run = "overmind s"

[tasks.workflow]
run = "python run.py"
