[project]
name = "golden"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "braintrust",
    "pydantic-ai",
]

[tool.uv.sources]
braintrust = { path = "../../py", editable = true }
