name: js-sdk-integration

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "The run ID of the js workflow build"
        required: false
        type: string
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  test-node-sdk-example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Determine artifact name
        id: artifact
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          ARTIFACT_NAME="javascript-sdk-dev-${RUN_ID}-22-dist"
          echo "name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"

      - name: Download javascript dist artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: sdk/js/artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install example dependencies
        working-directory: sdk/js/examples/otel
        run: npm install

      - name: Replace braintrust dist with build artifact
        working-directory: sdk/js/examples/otel
        env:
          ARTIFACT_NAME: ${{ steps.artifact.outputs.name }}
        run: |
          npm install "file:../../artifacts/${{ env.ARTIFACT_NAME }}"

      - name: Run NodeSDK example
        working-directory: sdk/js/examples/otel
        env:
          BRAINTRUST_OTEL_COMPAT: true
          BRAINTRUST_API_KEY: ${{ secrets.BRAINTRUST_API_KEY }}
        run: npm run sdk-example
