name: test-js-trigger

on:
  pull_request:
    paths-ignore:
      - "py/**"
      - "integrations/langchain-py/**"
      - "integrations/adk-py/**"
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Workflow
        run: echo "The test js trigger workflow ran"
